---

# based on this tutorial 
# https://easyengine.io/tutorials/linux/sysctl-conf
# https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt


- hosts: packer
  become: yes
  remote_user: vagrant
  vars_files:
    - '../vars/linux.yml'     
  tasks:

# Increase size of file handles and inode cache
    - sysctl:
        name: "fs.file-max"
        value: 394880
        sysctl_set: yes
        state: present
        reload: yes

# Do less swapping
    - sysctl:
        name: "vm.swappiness "
        value: 10
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "vm.dirty_ratio"
        value: 60
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "vm.dirty_background_ratio"
        value: 2
        sysctl_set: yes
        state: present
        reload: yes    

#Set amount of time to wait before reboot after a kernel panic       
    - sysctl:
        name: "kernel.panic"
        value: 30
        sysctl_set: yes
        state: present
        reload: yes

#Increase network buffer sizes
    - sysctl:
        name: "{{ item }}"
        value: 212992
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - "net.core.rmem_default"
        - "net.core.wmem_default"

    - sysctl:
        name: "{{ item }}"
        value: 212992
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - "net.core.rmem_max"
        - "net.core.wmem_max"

# Increase number of incoming connections
    - sysctl:
        name: "net.core.somaxconn"
        value: 128
        sysctl_set: yes
        state: present
        reload: yes

# Increase number of incoming connections backlog      
    - sysctl:
        name: "net.core.netdev_max_backlog"
        value: 1000
        sysctl_set: yes
        state: present
        reload: yes

# Increase the maximum amount of option memory buffers
    - sysctl:
        name: "net.core.optmem_max"
        value: 20480
        sysctl_set: yes
        state: present
        reload: yes  

# Ignore ICMP broadcast      
    - sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - "net.ipv4.icmp_echo_ignore_broadcasts"
        - "net.ipv4.icmp_ignore_bogus_error_responses"

# Protect from SYN floods DDOs
    - sysctl:
        name: "net.ipv4.tcp_syncookies"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "net.ipv4.tcp_max_syn_backlog"
        value: 128
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "net.ipv4.tcp_synack_retries"
        value: 3
        sysctl_set: yes
        state: present
        reload: yes

# Allowed local port range
    - sysctl:
        name: "net.ipv4.ip_local_port_range"
        value: "20000 65535"
        sysctl_set: yes
        state: present
        reload: yes

# Protect Against TCP Time-Wait
    - sysctl:
        name: "net.ipv4.tcp_rfc1337"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

# Decrease the time default value for tcp_fin_timeout connection
    - sysctl:
        name: "net.ipv4.tcp_fin_timeout"
        value: 15
        sysctl_set: yes
        state: present
        reload: yes

# Decrease the time default value for connections to keep alive
    - sysctl:
        name: "net.ipv4.tcp_keepalive_time"
        value: 300
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "net.ipv4.tcp_keepalive_probes"
        value: 5
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "net.ipv4.tcp_keepalive_intvl"
        value: 15
        sysctl_set: yes
        state: present
        reload: yes      
  

# Enable TCP window scaling
    - sysctl:
        name: "net.ipv4.tcp_window_scaling"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

# Increase the read/write buffers space allocatable
    - sysctl:
        name: "net.ipv4.tcp_rmem"
        value: "4096 87380 6291456"
        sysctl_set: yes
        state: present
        reload: yes
    - sysctl:
        name: "net.ipv4.tcp_wmem"
        value: "4096 16384 4194304"
        sysctl_set: yes
        state: present
        reload: yes  

# Increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
    - sysctl:
        name: "{{ item }}"
        value: 0
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
#        - "net.ipv4.tcp_tw_recycle" #disabled on kernel 4.12 and up
        - "net.ipv4.tcp_tw_reuse" 
    - sysctl:
        name: "net.ipv4.tcp_max_tw_buckets"
        value: 16384
        sysctl_set: yes
        state: present
        reload: yes      

...
