# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/focal64"
    ansible.vm.box_check_update = false
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.30.5", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "ubuntu/focal64"
    webserver.vm.box_check_update = false
    webserver.vm.hostname = "webserver"
    webserver.vm.network "private_network", ip: "192.168.30.6", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    webserver.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end  
end