# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.box_check_update = false
    centos.vm.hostname = "centosDisk"
    centos.vm.provider "virtualbox" do |vb|
      vb.name = "centos"
      vb.memory = "512"
      file_to_disk = "extradisk1.vmdk"
      unless File.exist?(file_to_disk)
          vb.customize [ "createmedium", "disk", "--filename", "extradisk1.vmdk", "--format", "vmdk", "--size", 1024 * 1 ]
      end
      vb.customize [ "storageattach", "centos" , "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.hostname = "ubuntuDisk"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu"
      vb.memory = "512"
      file_to_disk = "extradisk2.vmdk"
      unless File.exist?(file_to_disk)
          vb.customize [ "createmedium", "disk", "--filename", "extradisk2.vmdk", "--format", "vmdk", "--size", 1024 * 1 ]
      end
      vb.customize [ "storageattach", "ubuntu" , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
  end  
end
