# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server1" do |server1|
    server1.vm.box = "centos/8"
    server1.vm.box_check_update = false
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "192.168.30.5", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    server1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.box = "centos/8"
    server2.vm.box_check_update = false
    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "192.168.30.6", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    server2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end  
end
