# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/8"
    centos.vm.box_check_update = false
    centos.vm.hostname = "centos"
    centos.vm.network "private_network", ip: "2.2.2.2", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "3.3.3.3", nic_type: "virtio", virtualbox__intnet: "keepcoding"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.default_nic_type = "virtio"
    end
  end  
end
