#!/bin/bash

#Jesus García

#Write a countdown script. The script should use one argument (and not more than one). This argument specifies the number of minutes to count down. It should start with that #number of minutes and count down second by second, writing the text “there are nn seconds remaining” at every iteration. Use ​sleep to define the seconds. When there is no #more time left, the script should echo “time is over” and quit.

re='^[0-9]+$'
if [ "$#" -gt 1 ]
then
	echo "Just pass 1 parameter"
	exit 1
elif ! [[ $1 =~ $re ]]
then
	echo "$1 is not a number"
	exit 1
elif [ "$1" -lt 1 ]
then
	echo "Just pass a minute greater than 0"
	exit 1
else
	seconds=$(($1 * 60)) #We just have to multiply
	while [ $seconds -ne 0 ]
	do
		echo "There are $seconds seconds remaining"
		sleep 1
		seconds=$[$seconds-1]
	done
	echo "Time is over"
	exit 0	
fi
exit 0 